# Generated by Django 4.2.11 on 2024-03-12 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="image",
        ),
    ]
