# Generated by Django 4.2.11 on 2024-03-12 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_banner_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
